# Configuration Settings for C94-M8P device
ublox_gps_node:
  ros__parameters:
    debug: 0 # Range 0-4 (0 means no debug statements will print)
    device: /dev/ttyACM0
    frame_id: wgs84
    uart1:
      baudrate: 115200
      in: 32 # RTCM3
      out: 3 # UBX & NMEA

    rate: 4.0
    nav_rate: 1

    gnss:
      sbas: false
      gps: true
      galileo: true
      glonass: true
      qzss: true
      beidou: true

    dgnss_mode: 3 # RTK Fixed

    sbas:
      usage: 2 # Use diff corr

    dynamic_model: portable
    fix_mode: auto

    enable_ppp: false

    save_on_shutdown: false
    clear_bbr: false

    # TMODE3 Config
    tmode3: 0 # Disabled

    inf:
      all: true # Whether to display all INF messages in console
      debug: true
      error: true
      notice: true
      test: true
      warning: true

    publish:
      all: false
      aid: # Aiding data
        all: false
      rxm: # Reciever Manager
        all: false
      mon: # Monitoring
        all: false
      nav:
        all: true
